import { useState } from 'react';
import { FileText, ChevronDown, Download, Search } from 'lucide-react';
import { customers } from './data';
import { Sheet } from './components';
import { money, riskLabel } from './format';
import { modelVersion } from './ml-inference';
import type { CaseRecord } from './types';
import {
  askInvestigation,
  buildInvestigation,
  validateInvestigation,
  type Claim,
  type EvidenceSource,
} from './investigation';

function EvidenceClaim({ item, onSource }: { item: Claim; onSource: (id: string) => void }) {
  return (
    <div className="report-claim">
      <p>{item.text}</p>
      {item.sourceIds.length > 0 && (
        <details className="report-citations">
          <summary>Evidence sources ({item.sourceIds.length})</summary>
          <div className="report-sources">
            {item.sourceIds.map((id) => (
              <button
                key={id}
                type="button"
                onClick={() => onSource(id)}
                aria-label={`Inspect source ${id}`}
              >
                {id}
              </button>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
export function InvestigationPanel({
  record,
  onChange,
}: {
  record: CaseRecord;
  onChange: (c: CaseRecord, patch: Partial<CaseRecord>, message: string) => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const [error, setError] = useState('');
  const [source, setSource] = useState<EvidenceSource | null>(null);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<Claim[] | null>(null);
  let snapshot = record.investigation;
  let savedError = '';
  try {
    if (snapshot) validateInvestigation(snapshot, record);
  } catch (e) {
    snapshot = undefined;
    savedError = e instanceof Error ? e.message : 'Saved report could not be read.';
  }
  function generate() {
    try {
      const customer = customers.find((c) => c.id === record.customerId);
      if (!customer) throw new Error('The case customer is unavailable.');
      const investigation = buildInvestigation(record, customer, customers);
      onChange(
        record,
        { investigation },
        `Investigation report generated by ${investigation.reporter}; score provider ${investigation.evidence.risk.providerVersion}; evidence as of ${record.evidenceAsOf}; retrieval ${investigation.retrievalMs}ms, generation ${investigation.generationMs}ms. Human review required.`,
      );
      setError('');
      setAnswer(null);
      setSource(null);
      setExpanded(true);
    } catch (e) {
      setError(
        e instanceof Error
          ? e.message
          : 'Report generation failed. Existing case controls remain available.',
      );
    }
  }
  const onSource = (id: string) =>
    setSource(snapshot?.evidence.sources.find((s) => s.id === id) ?? null);
  const renderClaim = (item: Claim) => <EvidenceClaim item={item} onSource={onSource} />;
  const ask = (q: string) => {
    if (!snapshot || !q.trim()) return;
    setQuestion(q);
    setAnswer(askInvestigation(snapshot, q));
  };
  return (
    <section className="investigation-panel" aria-labelledby={`investigation-${record.id}`}>
      <div className="report-heading">
        <div>
          <span className="eyebrow">FROM RISK SCORE TO EVIDENCE</span>
          <h3 id={`investigation-${record.id}`}>
            <FileText size={17} aria-hidden="true" /> Investigation reporter
          </h3>
          <p>Local deterministic report · no LLM or external API</p>
        </div>
        {snapshot ? (
          <button
            className="secondary-button"
            type="button"
            aria-expanded={expanded}
            aria-controls={`report-${record.id}`}
            onClick={() => setExpanded(!expanded)}
          >
            {expanded ? 'Hide investigation' : 'View investigation'}{' '}
            <ChevronDown size={14} aria-hidden="true" />
          </button>
        ) : (
          <button className="primary-button" type="button" onClick={generate}>
            Generate investigation
          </button>
        )}
      </div>
      {(error || savedError) && (
        <p className="form-error" role="alert">
          {error || savedError}
        </p>
      )}
      {snapshot && expanded && (
        <div id={`report-${record.id}`} className="report-body">
          {snapshot.evidence.risk.providerVersion !== modelVersion && (
            <p className="report-notice">
              This saved report uses an earlier score provider ({snapshot.evidence.risk.providerVersion}).
              Current Customer 360 uses {modelVersion}. Use “Regenerate from captured date” to update
              this report while keeping its original evidence date.
            </p>
          )}
          <div className="report-notice">
            Automatically generated investigation assistance. Final decision requires human review.
            {snapshot.evidence.risk.source === 'model'
              ? ' Scores come from synthetic-trained models. Repayment estimates seven-day delinquency; scam is an episode peak. Real-world validity is unverified.'
              : ' Saved scores are simulated indices, not probabilities.'}
          </div>
          <div className="report-metadata">
            <span>
              <b>{snapshot.report.riskLevel}</b> review priority
            </span>
            <span>
              Scam <b>{riskLabel(snapshot.evidence.risk.scamScore)}/100</b>
            </span>
            <span>
              Repayment <b>{riskLabel(snapshot.evidence.risk.repaymentScore)}/100</b>
            </span>
            <span>
              Evidence as of{' '}
              <b>
                {new Date(snapshot.evidence.asOf).toLocaleString('en-IN', {
                  timeZone: 'Asia/Kolkata',
                })}{' '}
                IST
              </b>
            </span>
          </div>
          <h4>Executive summary</h4>
          {renderClaim(snapshot.report.executiveSummary)}
          <h4>Why this needs review</h4>
          <p className="report-caption">
            Observed signals and ledger findings; these do not reconstruct the score model’s feature
            contributions.
          </p>
          {snapshot.report.riskFactors.length ? (
            snapshot.report.riskFactors.map((factor, i) => (
              <div key={i} className="report-factor">
                <span className="badge neutral">{factor.severity}</span>
                {renderClaim(factor)}
              </div>
            ))
          ) : (
            <p>No additional risk contributor is established in the available records.</p>
          )}
          <h4>Configured baseline vs current</h4>
          <dl className="report-baseline">
            <div>
              <dt>Usual transfer · profile</dt>
              <dd>{money(snapshot.evidence.baseline.usualTransfer)}</dd>
            </div>
            <div>
              <dt>Trigger transfer</dt>
              <dd>
                {snapshot.evidence.triggerTransaction
                  ? `${snapshot.evidence.triggerTransaction.id} · ${money(snapshot.evidence.triggerTransaction.amount)}`
                  : 'Not available'}
              </dd>
            </div>
            <div>
              <dt>Salary / expense budget · profile</dt>
              <dd>
                {money(snapshot.evidence.baseline.salary)} /{' '}
                {money(snapshot.evidence.baseline.expenses)}
              </dd>
            </div>
          </dl>
          {renderClaim(snapshot.report.behavioralAnalysis)}
          <h4>Loan and financial position</h4>
          {renderClaim(snapshot.report.financialAnalysis)}
          <h4>Possible pattern · unconfirmed</h4>
          {renderClaim(snapshot.report.possiblePattern)}
          <details className="report-section">
            <summary>Supporting evidence ({snapshot.report.supportingEvidence.length})</summary>
            {snapshot.report.supportingEvidence.length ? (
              snapshot.report.supportingEvidence.map((item, i) => (
                <EvidenceClaim key={i} item={item} onSource={onSource} />
              ))
            ) : (
              <p>No transaction signals are recorded.</p>
            )}
          </details>
          <details className="report-section" open>
            <summary>Alternative and contradicting evidence</summary>
            {snapshot.report.alternatives.map((item, i) => (
              <EvidenceClaim key={i} item={item} onSource={onSource} />
            ))}
          </details>
          <details className="report-section">
            <summary>Device, merchant and recipient analysis</summary>
            <h4>Device</h4>
            {renderClaim(snapshot.report.deviceAnalysis)}
            <h4>Merchant</h4>
            {renderClaim(snapshot.report.merchantAnalysis)}
            <h4>Recipient relationships</h4>
            {snapshot.report.recipientAnalysis.map((item, i) => (
              <EvidenceClaim key={i} item={item} onSource={onSource} />
            ))}
          </details>
          <details className="report-section">
            <summary>
              Observed transaction and event timeline ({snapshot.report.timeline.length})
            </summary>
            <ol className="report-timeline">
              {snapshot.report.timeline.map((item) => (
                <li key={item.id}>
                  <span>
                    {new Date(item.at!).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST
                  </span>
                  <button type="button" onClick={() => onSource(item.id)}>
                    {item.label} · {item.id}
                  </button>
                </li>
              ))}
            </ol>
          </details>
          <details className="report-section">
            <summary>Missing evidence and limits</summary>
            <ul>
              {snapshot.evidence.gaps.map((gap) => (
                <li key={gap}>{gap}</li>
              ))}
            </ul>
          </details>
          <h4>Recommended investigation steps</h4>
          {snapshot.report.recommendedActions.map((item, i) => (
            <EvidenceClaim key={i} item={item} onSource={onSource} />
          ))}
          <div className="report-ask">
            <h4>Ask the case · local evidence lookup</h4>
            <p className="report-caption">
              Answers come only from this saved snapshot. Topic matching, not generative AI; no
              external search.
            </p>
            <div className="report-prompts">
              {[
                'Why was this flagged?',
                'What evidence suggests a false positive?',
                'Has this device appeared with other customers?',
                'What is the EMI shortfall?',
              ].map((q) => (
                <button type="button" key={q} onClick={() => ask(q)}>
                  {q}
                </button>
              ))}
            </div>
            <form
              onSubmit={(event) => {
                event.preventDefault();
                ask(question);
              }}
            >
              <label htmlFor={`case-question-${record.id}`}>Question or evidence source ID</label>
              <div>
                <input
                  id={`case-question-${record.id}`}
                  value={question}
                  onChange={(event) => setQuestion(event.target.value)}
                  maxLength={500}
                />
                <button type="submit" className="secondary-button" disabled={!question.trim()}>
                  <Search size={14} aria-hidden="true" /> Look up
                </button>
              </div>
            </form>
            <div aria-live="polite">
              {answer?.map((item, i) => (
                <EvidenceClaim key={i} item={item} onSource={onSource} />
              ))}
            </div>
          </div>
          <div className="report-footer">
            <span>
              Generated{' '}
              {new Date(snapshot.generatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}{' '}
              IST · {snapshot.reporter} · score provider {snapshot.evidence.risk.providerVersion}
            </span>
            <div>
              <button type="button" className="text-button" onClick={generate}>
                Regenerate from captured date
              </button>
              <button
                type="button"
                className="text-button"
                onClick={() => {
                  const blob = new Blob([JSON.stringify(snapshot, null, 2)], {
                    type: 'application/json',
                  });
                  const url = URL.createObjectURL(blob);
                  const link = document.createElement('a');
                  link.href = url;
                  link.download = `${record.id}-investigation.json`;
                  link.click();
                  setTimeout(() => URL.revokeObjectURL(url), 1000);
                }}
              >
                <Download size={14} aria-hidden="true" /> Export JSON
              </button>
            </div>
          </div>
          <p className="report-review">
            Record the final human decision using Disposition above and Analyst notes below.
            Generating or asking about a report never changes case status.
          </p>
        </div>
      )}
      <Sheet
        open={!!source}
        onClose={() => setSource(null)}
        title={source?.label ?? 'Evidence source'}
        description={
          source ? `Source ${source.id} · captured case ${record.id}` : 'Captured evidence'
        }
      >
        {source && (
          <div className="report-source-detail">
            <span className="eyebrow">
              {source.kind}
              {source.at
                ? ` · ${new Date(source.at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST`
                : ''}
            </span>
            <p>{source.details}</p>
            <p className="muted">
              This source belongs to the saved investigation snapshot, independent of the current
              replay day.
            </p>
          </div>
        )}
      </Sheet>
    </section>
  );
}
